server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka,http://eureka3000.com:3000/eureka  #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:

    instance-id: order-1 #此实例注册到eureka服务端的唯一的实例ID
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 1 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 3 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

spring:
  application:
    name: server-order #此实例注册到eureka服务端的name

feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000  # 方法调用超过这个时间，就会调用fallback
      circuitBreaker:
        requestVolumeThreshold: 5  #10秒内调用失败的次数超过5次，就会进入【熔断开启】状态。
#        sleepWindowInMilliseconds : 5000   时间

management:
  endpoints:
    web:
      exposure:
        include: '*'

